## Exploring Force Data
This notebook explores the Touch-Ex dataset numerical force data statistics.

In [1]:
# Allow imports from the parent directory
import sys
import os

module_path = os.path.abspath(os.path.join(".."))
sys.path.append(module_path)

In [2]:
# Imports
import data.utils as utils

In [3]:
# Load the dataset into DataFrames
dfs = utils.load_touch_ex_dataset()

In [4]:
# Extract the training and test_unseen DataFrames from the dictionary
train_df = dfs["train"]
test_unseen_df = dfs["test_unseen"]

In [5]:
# Get column names (same for both train_df and test_unseen_df)
train_df.columns

Index(['image', 'object', 'region', 'object_region', 'force_level', 'motion',
       'fsr_voltage', 'force_n', 'hardness', 'material', 'description',
       'interaction_num', 'frame_num', 'interaction_id'],
      dtype='str')

### FSR Voltage

In [6]:
train_df.groupby("force_level").agg({"fsr_voltage": ["mean", "std", "min", "max"]})

            fsr_voltage
                   mean       std       min       max
force_level
1              0.078906  0.174257  0.002417  0.989572
2              2.635507  0.383068  0.954122  3.055024
3              3.082861  0.034621  2.991375  3.170286

In [7]:
test_unseen_df.groupby("force_level").agg({"fsr_voltage": ["mean", "std", "min", "max"]})

            fsr_voltage
                   mean       std       min       max
force_level
1              0.038520  0.087663  0.002417  0.916255
2              2.863104  0.207242  1.174122  3.055024
3              3.100271  0.021981  3.055830  3.168675

### Force (Newtons)

In [8]:
train_df.groupby("force_level").agg({"force_n": ["mean", "std", "min", "max"]})

              force_n
                 mean       std       min        max
force_level
1            0.067722  0.148582  0.002009   0.824542
2            2.911721  0.955447  0.827141   5.440101
3            8.496956  2.360158  5.462320  14.715000

In [9]:
test_unseen_df.groupby("force_level").agg({"force_n": ["mean", "std", "min", "max"]})

              force_n
                 mean       std       min        max
force_level
1            0.034543  0.078611  0.002167   0.821652
2            3.333101  0.854343  1.052894   5.435793
3            8.437573  2.433737  5.462320  14.715000